#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_FPC1020)		+= fpc1020/
obj-$(CONFIG_FINGERPRINT_FPC1020_HYDROGEN)	+= fpc1020_hydrogen/
